/* Generated by pnpm gen:contract — do not edit. */
export default {
  "openapi": "3.0.0",
  "info": {
    "title": "Odyssey API",
    "version": "0.0.1"
  },
  "components": {
    "schemas": {
      "Error": {
        "type": "object",
        "properties": {
          "error": {
            "type": "string"
          }
        },
        "required": [
          "error"
        ]
      },
      "Order": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "customerName": {
            "type": "string"
          },
          "status": {
            "type": "string",
            "enum": [
              "pending",
              "accepted",
              "preparing",
              "ready",
              "completed",
              "cancelled"
            ]
          },
          "total": {
            "type": "number"
          },
          "createdAt": {
            "type": "string"
          },
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "quantity": {
                  "type": "integer"
                },
                "unitPrice": {
                  "type": "number"
                },
                "subtotal": {
                  "type": "number"
                }
              },
              "required": [
                "name",
                "quantity",
                "unitPrice",
                "subtotal"
              ]
            }
          }
        },
        "required": [
          "id",
          "customerName",
          "status",
          "total",
          "createdAt",
          "items"
        ]
      },
      "Customer": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "ordersCount": {
            "type": "integer"
          },
          "totalSpend": {
            "type": "number"
          },
          "lastOrderDate": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "name",
          "email",
          "phone",
          "ordersCount",
          "totalSpend",
          "lastOrderDate"
        ]
      },
      "MenuCategory": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "sortOrder": {
            "type": "integer"
          },
          "itemCount": {
            "type": "integer"
          }
        },
        "required": [
          "id",
          "name",
          "description",
          "sortOrder",
          "itemCount"
        ]
      },
      "MenuItem": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "price": {
            "type": "number"
          },
          "available": {
            "type": "boolean"
          },
          "category": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "name",
          "price",
          "available",
          "category"
        ]
      },
      "Settings": {
        "type": "object",
        "properties": {
          "prepTimeMinutes": {
            "type": "integer",
            "minimum": 1
          },
          "autoAccept": {
            "type": "boolean"
          },
          "serviceAvailable": {
            "type": "boolean"
          },
          "openingHours": {
            "type": "string"
          }
        },
        "required": [
          "prepTimeMinutes",
          "autoAccept",
          "serviceAvailable",
          "openingHours"
        ]
      },
      "Summary": {
        "type": "object",
        "properties": {
          "ordersToday": {
            "type": "integer"
          },
          "revenueToday": {
            "type": "number"
          },
          "pendingOrders": {
            "type": "integer"
          },
          "popularItems": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "count": {
                  "type": "integer"
                }
              },
              "required": [
                "name",
                "count"
              ]
            }
          },
          "recentOrders": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "customerName": {
                  "type": "string"
                },
                "status": {
                  "type": "string",
                  "enum": [
                    "pending",
                    "accepted",
                    "preparing",
                    "ready",
                    "completed",
                    "cancelled"
                  ]
                },
                "total": {
                  "type": "number"
                },
                "createdAt": {
                  "type": "string"
                },
                "items": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "quantity": {
                        "type": "integer"
                      },
                      "unitPrice": {
                        "type": "number"
                      },
                      "subtotal": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "name",
                      "quantity",
                      "unitPrice",
                      "subtotal"
                    ]
                  }
                }
              },
              "required": [
                "id",
                "customerName",
                "status",
                "total",
                "createdAt",
                "items"
              ]
            }
          }
        },
        "required": [
          "ordersToday",
          "revenueToday",
          "pendingOrders",
          "popularItems",
          "recentOrders"
        ]
      }
    },
    "parameters": {}
  },
  "paths": {
    "/health": {
      "get": {
        "summary": "Health check",
        "responses": {
          "200": {
            "description": "Service healthy",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "service": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "status",
                    "service"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/orders": {
      "get": {
        "summary": "List orders",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "enum": [
                "pending",
                "accepted",
                "preparing",
                "ready",
                "completed",
                "cancelled"
              ]
            },
            "required": false,
            "name": "status",
            "in": "query"
          },
          {
            "schema": {
              "type": "integer",
              "minimum": 0,
              "exclusiveMinimum": true
            },
            "required": false,
            "name": "customerId",
            "in": "query"
          },
          {
            "schema": {
              "type": "string"
            },
            "required": false,
            "name": "search",
            "in": "query"
          },
          {
            "schema": {
              "type": "string"
            },
            "required": false,
            "name": "from",
            "in": "query"
          },
          {
            "schema": {
              "type": "string"
            },
            "required": false,
            "name": "to",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Orders list",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "customerName": {
                        "type": "string"
                      },
                      "status": {
                        "type": "string",
                        "enum": [
                          "pending",
                          "accepted",
                          "preparing",
                          "ready",
                          "completed",
                          "cancelled"
                        ]
                      },
                      "total": {
                        "type": "number"
                      },
                      "createdAt": {
                        "type": "string"
                      },
                      "items": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "name": {
                              "type": "string"
                            },
                            "quantity": {
                              "type": "integer"
                            },
                            "unitPrice": {
                              "type": "number"
                            },
                            "subtotal": {
                              "type": "number"
                            }
                          },
                          "required": [
                            "name",
                            "quantity",
                            "unitPrice",
                            "subtotal"
                          ]
                        }
                      }
                    },
                    "required": [
                      "id",
                      "customerName",
                      "status",
                      "total",
                      "createdAt",
                      "items"
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create an order",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "customerId": {
                    "type": "integer",
                    "minimum": 0,
                    "exclusiveMinimum": true
                  },
                  "items": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "menuItemId": {
                          "type": "integer",
                          "minimum": 0,
                          "exclusiveMinimum": true
                        },
                        "quantity": {
                          "type": "integer",
                          "minimum": 0,
                          "exclusiveMinimum": true
                        }
                      },
                      "required": [
                        "menuItemId",
                        "quantity"
                      ]
                    },
                    "minItems": 1
                  }
                },
                "required": [
                  "customerId",
                  "items"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Order created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "customerName": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "pending",
                        "accepted",
                        "preparing",
                        "ready",
                        "completed",
                        "cancelled"
                      ]
                    },
                    "total": {
                      "type": "number"
                    },
                    "createdAt": {
                      "type": "string"
                    },
                    "items": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "name": {
                            "type": "string"
                          },
                          "quantity": {
                            "type": "integer"
                          },
                          "unitPrice": {
                            "type": "number"
                          },
                          "subtotal": {
                            "type": "number"
                          }
                        },
                        "required": [
                          "name",
                          "quantity",
                          "unitPrice",
                          "subtotal"
                        ]
                      }
                    }
                  },
                  "required": [
                    "id",
                    "customerName",
                    "status",
                    "total",
                    "createdAt",
                    "items"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Business rule violation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/orders/{id}/accept": {
      "post": {
        "summary": "accept an order",
        "parameters": [
          {
            "schema": {
              "type": "integer",
              "minimum": 0,
              "exclusiveMinimum": true
            },
            "required": true,
            "name": "id",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Order updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "customerName": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "pending",
                        "accepted",
                        "preparing",
                        "ready",
                        "completed",
                        "cancelled"
                      ]
                    },
                    "total": {
                      "type": "number"
                    },
                    "createdAt": {
                      "type": "string"
                    },
                    "items": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "name": {
                            "type": "string"
                          },
                          "quantity": {
                            "type": "integer"
                          },
                          "unitPrice": {
                            "type": "number"
                          },
                          "subtotal": {
                            "type": "number"
                          }
                        },
                        "required": [
                          "name",
                          "quantity",
                          "unitPrice",
                          "subtotal"
                        ]
                      }
                    }
                  },
                  "required": [
                    "id",
                    "customerName",
                    "status",
                    "total",
                    "createdAt",
                    "items"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Invalid transition",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/orders/{id}/prepare": {
      "post": {
        "summary": "prepare an order",
        "parameters": [
          {
            "schema": {
              "type": "integer",
              "minimum": 0,
              "exclusiveMinimum": true
            },
            "required": true,
            "name": "id",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Order updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "customerName": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "pending",
                        "accepted",
                        "preparing",
                        "ready",
                        "completed",
                        "cancelled"
                      ]
                    },
                    "total": {
                      "type": "number"
                    },
                    "createdAt": {
                      "type": "string"
                    },
                    "items": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "name": {
                            "type": "string"
                          },
                          "quantity": {
                            "type": "integer"
                          },
                          "unitPrice": {
                            "type": "number"
                          },
                          "subtotal": {
                            "type": "number"
                          }
                        },
                        "required": [
                          "name",
                          "quantity",
                          "unitPrice",
                          "subtotal"
                        ]
                      }
                    }
                  },
                  "required": [
                    "id",
                    "customerName",
                    "status",
                    "total",
                    "createdAt",
                    "items"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Invalid transition",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/orders/{id}/ready": {
      "post": {
        "summary": "ready an order",
        "parameters": [
          {
            "schema": {
              "type": "integer",
              "minimum": 0,
              "exclusiveMinimum": true
            },
            "required": true,
            "name": "id",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Order updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "customerName": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "pending",
                        "accepted",
                        "preparing",
                        "ready",
                        "completed",
                        "cancelled"
                      ]
                    },
                    "total": {
                      "type": "number"
                    },
                    "createdAt": {
                      "type": "string"
                    },
                    "items": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "name": {
                            "type": "string"
                          },
                          "quantity": {
                            "type": "integer"
                          },
                          "unitPrice": {
                            "type": "number"
                          },
                          "subtotal": {
                            "type": "number"
                          }
                        },
                        "required": [
                          "name",
                          "quantity",
                          "unitPrice",
                          "subtotal"
                        ]
                      }
                    }
                  },
                  "required": [
                    "id",
                    "customerName",
                    "status",
                    "total",
                    "createdAt",
                    "items"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Invalid transition",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/orders/{id}/complete": {
      "post": {
        "summary": "complete an order",
        "parameters": [
          {
            "schema": {
              "type": "integer",
              "minimum": 0,
              "exclusiveMinimum": true
            },
            "required": true,
            "name": "id",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Order updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "customerName": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "pending",
                        "accepted",
                        "preparing",
                        "ready",
                        "completed",
                        "cancelled"
                      ]
                    },
                    "total": {
                      "type": "number"
                    },
                    "createdAt": {
                      "type": "string"
                    },
                    "items": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "name": {
                            "type": "string"
                          },
                          "quantity": {
                            "type": "integer"
                          },
                          "unitPrice": {
                            "type": "number"
                          },
                          "subtotal": {
                            "type": "number"
                          }
                        },
                        "required": [
                          "name",
                          "quantity",
                          "unitPrice",
                          "subtotal"
                        ]
                      }
                    }
                  },
                  "required": [
                    "id",
                    "customerName",
                    "status",
                    "total",
                    "createdAt",
                    "items"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Invalid transition",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/orders/{id}/cancel": {
      "post": {
        "summary": "cancel an order",
        "parameters": [
          {
            "schema": {
              "type": "integer",
              "minimum": 0,
              "exclusiveMinimum": true
            },
            "required": true,
            "name": "id",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Order updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "customerName": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "pending",
                        "accepted",
                        "preparing",
                        "ready",
                        "completed",
                        "cancelled"
                      ]
                    },
                    "total": {
                      "type": "number"
                    },
                    "createdAt": {
                      "type": "string"
                    },
                    "items": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "name": {
                            "type": "string"
                          },
                          "quantity": {
                            "type": "integer"
                          },
                          "unitPrice": {
                            "type": "number"
                          },
                          "subtotal": {
                            "type": "number"
                          }
                        },
                        "required": [
                          "name",
                          "quantity",
                          "unitPrice",
                          "subtotal"
                        ]
                      }
                    }
                  },
                  "required": [
                    "id",
                    "customerName",
                    "status",
                    "total",
                    "createdAt",
                    "items"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Invalid transition",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/customers": {
      "get": {
        "summary": "List customers",
        "responses": {
          "200": {
            "description": "Customers list",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "name": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "phone": {
                        "type": "string"
                      },
                      "ordersCount": {
                        "type": "integer"
                      },
                      "totalSpend": {
                        "type": "number"
                      },
                      "lastOrderDate": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "name",
                      "email",
                      "phone",
                      "ordersCount",
                      "totalSpend",
                      "lastOrderDate"
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/customers/{id}/orders": {
      "get": {
        "summary": "List orders for a customer",
        "parameters": [
          {
            "schema": {
              "type": "integer",
              "minimum": 0,
              "exclusiveMinimum": true
            },
            "required": true,
            "name": "id",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Customer orders",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "customerName": {
                        "type": "string"
                      },
                      "status": {
                        "type": "string",
                        "enum": [
                          "pending",
                          "accepted",
                          "preparing",
                          "ready",
                          "completed",
                          "cancelled"
                        ]
                      },
                      "total": {
                        "type": "number"
                      },
                      "createdAt": {
                        "type": "string"
                      },
                      "items": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "name": {
                              "type": "string"
                            },
                            "quantity": {
                              "type": "integer"
                            },
                            "unitPrice": {
                              "type": "number"
                            },
                            "subtotal": {
                              "type": "number"
                            }
                          },
                          "required": [
                            "name",
                            "quantity",
                            "unitPrice",
                            "subtotal"
                          ]
                        }
                      }
                    },
                    "required": [
                      "id",
                      "customerName",
                      "status",
                      "total",
                      "createdAt",
                      "items"
                    ]
                  }
                }
              }
            }
          },
          "404": {
            "description": "Customer not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/categories": {
      "get": {
        "summary": "List menu categories",
        "responses": {
          "200": {
            "description": "Categories list",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "name": {
                        "type": "string"
                      },
                      "description": {
                        "type": "string"
                      },
                      "sortOrder": {
                        "type": "integer"
                      },
                      "itemCount": {
                        "type": "integer"
                      }
                    },
                    "required": [
                      "id",
                      "name",
                      "description",
                      "sortOrder",
                      "itemCount"
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create a menu category",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "maxLength": 120
                  },
                  "description": {
                    "type": "string"
                  },
                  "sortOrder": {
                    "type": "integer"
                  }
                },
                "required": [
                  "name",
                  "description",
                  "sortOrder"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Category created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "sortOrder": {
                      "type": "integer"
                    },
                    "itemCount": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "description",
                    "sortOrder",
                    "itemCount"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Unable to create category",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/categories/{id}": {
      "patch": {
        "summary": "Update a menu category",
        "parameters": [
          {
            "schema": {
              "type": "integer",
              "minimum": 0,
              "exclusiveMinimum": true
            },
            "required": true,
            "name": "id",
            "in": "path"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "maxLength": 120
                  },
                  "description": {
                    "type": "string"
                  },
                  "sortOrder": {
                    "type": "integer"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Category updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "sortOrder": {
                      "type": "integer"
                    },
                    "itemCount": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "description",
                    "sortOrder",
                    "itemCount"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Unable to update category",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/menu-items": {
      "get": {
        "summary": "List menu items",
        "responses": {
          "200": {
            "description": "Menu items list",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "name": {
                        "type": "string"
                      },
                      "description": {
                        "type": "string"
                      },
                      "price": {
                        "type": "number"
                      },
                      "available": {
                        "type": "boolean"
                      },
                      "category": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "name",
                      "price",
                      "available",
                      "category"
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create a menu item",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 1
                  },
                  "description": {
                    "type": "string",
                    "minLength": 1
                  },
                  "price": {
                    "type": "number",
                    "minimum": 0,
                    "exclusiveMinimum": true
                  },
                  "available": {
                    "type": "boolean"
                  },
                  "category": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "name",
                  "description",
                  "price",
                  "available",
                  "category"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Menu item created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "price": {
                      "type": "number"
                    },
                    "available": {
                      "type": "boolean"
                    },
                    "category": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "price",
                    "available",
                    "category"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Invalid menu item payload",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/menu-items/{id}": {
      "patch": {
        "summary": "Update a menu item",
        "parameters": [
          {
            "schema": {
              "type": "integer",
              "minimum": 0,
              "exclusiveMinimum": true
            },
            "required": true,
            "name": "id",
            "in": "path"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 1
                  },
                  "description": {
                    "type": "string",
                    "minLength": 1
                  },
                  "price": {
                    "type": "number",
                    "minimum": 0,
                    "exclusiveMinimum": true
                  },
                  "available": {
                    "type": "boolean"
                  },
                  "category": {
                    "type": "string",
                    "minLength": 1
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Menu item updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "price": {
                      "type": "number"
                    },
                    "available": {
                      "type": "boolean"
                    },
                    "category": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "price",
                    "available",
                    "category"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Invalid menu item update",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/settings": {
      "get": {
        "summary": "Get settings",
        "responses": {
          "200": {
            "description": "Settings payload",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "prepTimeMinutes": {
                      "type": "integer",
                      "minimum": 1
                    },
                    "autoAccept": {
                      "type": "boolean"
                    },
                    "serviceAvailable": {
                      "type": "boolean"
                    },
                    "openingHours": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "prepTimeMinutes",
                    "autoAccept",
                    "serviceAvailable",
                    "openingHours"
                  ]
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Update settings",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "prepTimeMinutes": {
                    "type": "integer",
                    "minimum": 0,
                    "exclusiveMinimum": true
                  },
                  "autoAccept": {
                    "type": "boolean"
                  },
                  "serviceAvailable": {
                    "type": "boolean"
                  },
                  "openingHours": {
                    "type": "string",
                    "minLength": 1
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Settings updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "prepTimeMinutes": {
                      "type": "integer",
                      "minimum": 1
                    },
                    "autoAccept": {
                      "type": "boolean"
                    },
                    "serviceAvailable": {
                      "type": "boolean"
                    },
                    "openingHours": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "prepTimeMinutes",
                    "autoAccept",
                    "serviceAvailable",
                    "openingHours"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Invalid settings payload",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/summary": {
      "get": {
        "summary": "Get home summary",
        "responses": {
          "200": {
            "description": "Summary payload",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "ordersToday": {
                      "type": "integer"
                    },
                    "revenueToday": {
                      "type": "number"
                    },
                    "pendingOrders": {
                      "type": "integer"
                    },
                    "popularItems": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "name": {
                            "type": "string"
                          },
                          "count": {
                            "type": "integer"
                          }
                        },
                        "required": [
                          "name",
                          "count"
                        ]
                      }
                    },
                    "recentOrders": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "customerName": {
                            "type": "string"
                          },
                          "status": {
                            "type": "string",
                            "enum": [
                              "pending",
                              "accepted",
                              "preparing",
                              "ready",
                              "completed",
                              "cancelled"
                            ]
                          },
                          "total": {
                            "type": "number"
                          },
                          "createdAt": {
                            "type": "string"
                          },
                          "items": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "properties": {
                                "name": {
                                  "type": "string"
                                },
                                "quantity": {
                                  "type": "integer"
                                },
                                "unitPrice": {
                                  "type": "number"
                                },
                                "subtotal": {
                                  "type": "number"
                                }
                              },
                              "required": [
                                "name",
                                "quantity",
                                "unitPrice",
                                "subtotal"
                              ]
                            }
                          }
                        },
                        "required": [
                          "id",
                          "customerName",
                          "status",
                          "total",
                          "createdAt",
                          "items"
                        ]
                      }
                    }
                  },
                  "required": [
                    "ordersToday",
                    "revenueToday",
                    "pendingOrders",
                    "popularItems",
                    "recentOrders"
                  ]
                }
              }
            }
          }
        }
      }
    }
  }
} as const
